version: "3.9"
services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - 127.0.0.1:3000:3000

  frontend:
    build:
      context: frontend
      dockerfile: Dockerfile
    ports:
      - 127.0.0.1:8080:8080

volumes:
  db-store:
